# Generated by Django 4.1.2 on 2022-10-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
                ('mobile_phone', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('national_id', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('role', models.CharField(max_length=4)),
                ('code', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('status', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('terminated_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
